---
kind: pipeline
name: default

services:
- name: broker
  image: eclipse-mosquitto

steps:
- name: run tests
  image: alpine:latest
  commands:
  - apk add --no-cache python3
  - cp -r /drone/src /tmp/src
  - pip3 install --no-cache-dir -r /tmp/src/requirements.txt
  - pip3 install --no-cache-dir behave
  - mv /tmp/src/config.tests.toml /tmp/src/config.toml
  - cd /tmp/src && python3 -m behave

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/mqtt-pushgateway
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/mqtt-pushgateway:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 08431f201762d04937c91712bd562f1ac689ddab046de1cc06f74fdfbd3f2853

...
