---
kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/mqtt-pushgateway
    tags: latest
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 690ac2c10c20711c0e5ec9d8e46c5f6135fae46493a9f239f601b5c227d23103

...
