# config.toml used for integration tests. See config.example.toml for
# one that is more useful for you.

[exporter]
listen = "0.0.0.0"
port   = 9466

[mqtt]
client_id = "mqtt_pushgw-%(hostname)s"
broker    = "broker"
port      = 1883
username  = ""
password  = ""

subscribe = [
    'sensor/#',
    'zigbee2mqtt/#',
    "otherTopic"
]

expire = 300

[[topic]]
match  = 'sensor/(?P<sensor_name>\w+)/(?P<__metric__>\w+)'

[[topic]]
match  = 'sensor/slow_sensor/super_slow_metric'
expire = 900
metric = "just_a_metric"

[[topic]]
match  = 'sensor/sucky_sensor/.*'
ignore = true
